name: Deploy WaaS Docs to s3

on:
  workflow_dispatch:

  pull_request:
    types: [opened, reopened]

  push:
    branches:
      - main

jobs:
  github-action-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: dumps links
        run: |-
          echo "on pull request number: ${{ github.event.number }}"
          echo "links"
          echo "${{ github.server_url }}/${{ github.repository }}/pulls/"

      - name: on pull request
        if: github.event_name == 'pull_request'
        run: |-
          echo "on pull request number: ${{ github.event.number }}"
          echo "links"
          echo "${{ github.server_url }}/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}"
