name: Github action link dumps test
on:
  workflow_dispatch:

  pull_request:
    types: [opened, reopened]

  push:
    branches:
      - main

jobs:
  github-action-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: dumps links
        run: |-
          echo "on pull request number: ${{ github.event.number }}" 
          echo "dump links" >> message.txt

      - name: on pull request
        if: github.event_name == 'pull_request'
        run: |-
          echo "on pull request number: ${{ github.event.number }}" >> message.txt
          echo "links" >> message.txt
          echo "${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.pull_request.number }}" >> message.txt

      - name: read message
        run: |-
          cat message.txt
